apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportengineuivmss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportengineuivmss
  template:
    metadata:
      labels:
        app: reportengineuivmss
    spec:
      containers:
        - name: reportengineuivmss
          image: taodev.azurecr.io/reportengineuivmss:$tag
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret
      nodeSelector:
        agentpool: taodev